### ISSUE TITLE
Add youtube-nocookie support

### ISSUE THREAD

**Issue by onedrawingperday** [isometrixk/mediaswipe#1]
First of all thank you for the great plugin.

Is there a way to have the YouTube iframe use the privacy enhanced mode `www.youtube-nocookie.com`?

Using this Google domain allows embedding of YouTube videos without setting cookies in a visitor's device. It sets Local Storage items when the visitor starts playing the video.

**Comment by isometrixk** [comment]
Hey thanks! Currently there isn't support but it won't be hard to implement - I'll take a look into this tonight.

**Comment by onedrawingperday** [comment]
As I understand it youtube API does not allow for using the `www.youtube-nocookie.com` domain.

So I'm closing this issue (I don't like having issues open forever).

Again thanks very much for the plugin.
